### ISSUE TITLE
[Feature Request] Support banner plugin

### ISSUE THREAD

**Issue by Quorafind** [yo-goto/obsidian-card-view-mode#2]
Is it doable to support banner plugin? https://github.com/noatpad/obsidian-banners/tree/1.0.0

**Comment by yo-goto** [comment]
Really Cool!
I'll try supporting banner!

**Comment by yo-goto** [comment]
I made card view style compatible with Banner plugin in [the new release](https://github.com/yo-goto/obsidian-card-view-mode/releases/tag/0.4.7).

<img src="https://user-images.githubusercontent.com/50942816/134031769-994318ac-88bd-45e3-b038-609241749fb5.png" width="400px" height="auto">
